# Colten Wasden
cleanup of the inflation dataset

In [19]:
import numpy as np
import pandas as pd

In [20]:
inflation_labels = {}
# reading txt doc and creating a dict to map onto dataset
with open('inflation_ids.txt', 'r') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        
        label, code = line.rsplit(' - ', 1)
        inflation_labels[code.strip()] = label.strip()

print(inflation_labels)

{'APU0000704111': 'Bacon, sliced, per lb.', 'APU0000711211': 'Bananas, per lb.', 'APU0000702111': 'Bread, white, pan, per lb.', 'APU0000706111': 'Chicken, fresh, whole, per lb.', 'APU0000717311': 'Coffee, 100%, ground roast, all sizes, per lb.', 'APU0000708111': 'Eggs, grade A, large, per doz.', 'APU0000701111': 'Flour, white, all purpose, per lb.', 'APU0000709112': 'Milk, fresh, whole, fortified, per gal.', 'APU0000711311': 'Oranges, navel, per lb.', 'APU0000701312': 'Rice, white, long grain, uncooked, per lb.', 'APU0000712311': 'Tomatoes, field grown, per lb.', 'APU000072610': 'Electricity per KWH', 'APU000072511': 'Fuel oil #2 per gallon', 'APU00007471A': 'Gasoline, all types, per gallon', 'APU000074714': 'Gasoline, unleaded regular, per gallon'}

In [21]:
inflation_df = pd.read_csv('Dataset #2 - inflation.txt')
inflation_df = inflation_df.rename(columns={'Series ID': 'series_id'})

#mapping labels onto correlating rows in dataset

inflation_df.insert(1, 'label', inflation_df['series_id'].map(inflation_labels))
inflation_df.head()

,series_id,label,Jan 2016,Feb 2016,Mar 2016,Apr 2016,May 2016,Jun 2016,Jul 2016,Aug 2016,...,Mar 2026,Apr 2026,May 2026,Jun 2026,Jul 2026,Aug 2026,Sep 2026,Oct 2026,Nov 2026,Dec 2026
0,APU0000704111,"Bacon, sliced, per lb.",5.656,5.394,5.494,5.613,5.552,5.374,5.454,5.448,...,6.801,6.826,,,,,,,,
1,APU0000711211,"Bananas, per lb.",0.581,0.573,0.586,0.574,0.570,0.569,0.567,0.562,...,0.657,0.654,,,,,,,,
2,APU0000702111,"Bread, white, pan, per lb.",1.425,1.407,1.416,1.406,1.382,1.333,1.349,1.341,...,1.808,1.869,,,,,,,,
3,APU0000706111,"Chicken, fresh, whole, per lb.",1.429,1.478,1.463,1.496,1.489,1.408,1.445,1.426,...,2.033,2.026,,,,,,,,
4,APU0000717311,"Coffee, 100%, ground roast, all sizes, per lb.",4.498,4.447,4.405,4.428,4.443,4.481,4.428,4.316,...,9.608,9.723,,,,,,,,

In [ ]:
earnings = pd.read_csv('Dataset #1 - earnings.txt')
earn_labels = pd.read_csv('earnings_ids.txt', sep='\t')
print(earnings.head())
print(earn_labels.head())

       Series ID  Jan 2016  Feb 2016  Mar 2016  Apr 2016  May 2016  Jun 2016  \
0  CEU0000000001  141073.0  141900.0  142797.0  143892.0  144541.0  145205.0
1  CES0000000001  143210.0  143406.0  143662.0  143854.0  143900.0  144147.0
2  CEU0500000001  119093.0  119487.0  120245.0  121313.0  122001.0  123099.0
3  CES0500000001  121096.0  121268.0  121484.0  121670.0  121701.0  121967.0
4  CEU0600000001   19238.0   19214.0   19341.0   19551.0   19707.0   19985.0

   Jul 2016  Aug 2016  Sep 2016  ...   Mar 2026   Apr 2026  May 2026  \
0  144232.0  144484.0  145149.0  ...  157769(P)  158695(P)
1  144520.0  144661.0  144967.0  ...  158621(P)  158736(P)
2  123232.0  123281.0  122910.0  ...  134125(P)  135049(P)
3  122231.0  122377.0  122644.0  ...  135305(P)  135428(P)
4   20065.0   20062.0   19976.0  ...   21239(P)   21401(P)

   Jun 2026  Jul 2026  Aug 2026  Sep 2026  Oct 2026  Nov 2026  Dec 2026
0
1
2
3
4

[5 rows x 133 columns]
  CES Industry Code NAICS Code (1)         CES Industry Title  \
0         00-000000            NaN              Total nonfarm
1         05-000000            NaN              Total private
2         06-000000            NaN            Goods-producing
3         07-000000            NaN          Service-providing
4         08-000000            NaN  Private service-providing

                    Ownership Next Highest Published Level  \
0  Private and all government                          NaN
1                     Private                    00-000000
2                     Private                    05-000000
3  Private and all government                    00-000000
4                     Private                    05-000000

  NSA Published Series SA Published Series (2)  Start Year of AE Series
0                    B                       B                     1939
1                    A                       A                     1939
2                    A                       A                     1939
3                    B                       B                     1939
4                    A                       A                     1939

In [ ]:
##Cleaning up the earnings df before merging

date_cols = earnings.columns[1:]                      
# everything except Series ID

earnings[date_cols] = (
    earnings[date_cols]
    .replace(r"\(P\)", "", regex=True)          # drop (P) in earnings noted as preliminary
    .replace(r"^\s*$", pd.NA, regex=True)       # blank trailing months -> NA
    .apply(pd.to_numeric, errors="coerce")
)
earnings.head()

,Series ID,Jan 2016,Feb 2016,Mar 2016,Apr 2016,May 2016,Jun 2016,Jul 2016,Aug 2016,Sep 2016,...,Mar 2026,Apr 2026,May 2026,Jun 2026,Jul 2026,Aug 2026,Sep 2026,Oct 2026,Nov 2026,Dec 2026
0,CEU0000000001,141073.0,141900.0,142797.0,143892.0,144541.0,145205.0,144232.0,144484.0,145149.0,...,157769.0,158695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CES0000000001,143210.0,143406.0,143662.0,143854.0,143900.0,144147.0,144520.0,144661.0,144967.0,...,158621.0,158736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CEU0500000001,119093.0,119487.0,120245.0,121313.0,122001.0,123099.0,123232.0,123281.0,122910.0,...,134125.0,135049.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CES0500000001,121096.0,121268.0,121484.0,121670.0,121701.0,121967.0,122231.0,122377.0,122644.0,...,135305.0,135428.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CEU0600000001,19238.0,19214.0,19341.0,19551.0,19707.0,19985.0,20065.0,20062.0,19976.0,...,21239.0,21401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Merging earnings df and label df.
earnings["industry_code"] = earnings["Series ID"].str[3:11]     #industry code is embedded in the SeriesID
earnings["seasonal"]      = earnings["Series ID"].str[2]   # U = NSA, S = SA -- encoded in series id to inform if seasonal or not
earnings.insert(0, "industry_code", earnings.pop("industry_code"))
earnings.insert(1, "seasonal", earnings.pop("seasonal"))

earnings.head()

/var/folders/7j/6mqynt1d3rn3g84946r88qxr0000gn/T/ipykernel_1612/2720948915.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  earnings.insert(0, "industry_code", earnings.pop("industry_code"))
/var/folders/7j/6mqynt1d3rn3g84946r88qxr0000gn/T/ipykernel_1612/2720948915.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  earnings.insert(1, "seasonal", earnings.pop("seasonal"))

,industry_code,seasonal,Series ID,Jan 2016,Feb 2016,Mar 2016,Apr 2016,May 2016,Jun 2016,Jul 2016,...,Mar 2026,Apr 2026,May 2026,Jun 2026,Jul 2026,Aug 2026,Sep 2026,Oct 2026,Nov 2026,Dec 2026
0,00000000,U,CEU0000000001,141073.0,141900.0,142797.0,143892.0,144541.0,145205.0,144232.0,...,157769.0,158695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00000000,S,CES0000000001,143210.0,143406.0,143662.0,143854.0,143900.0,144147.0,144520.0,...,158621.0,158736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,05000000,U,CEU0500000001,119093.0,119487.0,120245.0,121313.0,122001.0,123099.0,123232.0,...,134125.0,135049.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,05000000,S,CES0500000001,121096.0,121268.0,121484.0,121670.0,121701.0,121967.0,122231.0,...,135305.0,135428.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,06000000,U,CEU0600000001,19238.0,19214.0,19341.0,19551.0,19707.0,19985.0,20065.0,...,21239.0,21401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# normalize lookup key and merge
earn_labels["industry_code"] = earn_labels["CES Industry Code"].str.strip().str.replace("-", "", regex=False)
earnings_clean = earnings.merge(
    earn_labels[["industry_code", "CES Industry Title"]].drop_duplicates("industry_code"),
    on="industry_code", how="left",
)
earnings_clean.insert(0, "CES Industry Title", earnings_clean.pop("CES Industry Title"))

earnings_clean.head()

,CES Industry Title,industry_code,seasonal,Series ID,Jan 2016,Feb 2016,Mar 2016,Apr 2016,May 2016,Jun 2016,...,Mar 2026,Apr 2026,May 2026,Jun 2026,Jul 2026,Aug 2026,Sep 2026,Oct 2026,Nov 2026,Dec 2026
0,Total nonfarm,00000000,U,CEU0000000001,141073.0,141900.0,142797.0,143892.0,144541.0,145205.0,...,157769.0,158695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total nonfarm,00000000,S,CES0000000001,143210.0,143406.0,143662.0,143854.0,143900.0,144147.0,...,158621.0,158736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total private,05000000,U,CEU0500000001,119093.0,119487.0,120245.0,121313.0,122001.0,123099.0,...,134125.0,135049.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total private,05000000,S,CES0500000001,121096.0,121268.0,121484.0,121670.0,121701.0,121967.0,...,135305.0,135428.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Goods-producing,06000000,U,CEU0600000001,19238.0,19214.0,19341.0,19551.0,19707.0,19985.0,...,21239.0,21401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# verifying no NA in industry title
earnings_clean["CES Industry Title"].isna().sum()

np.int64(0)