# Regional Housing Affordability Analysis

This notebook examines regional differences in housing affordability
across U.S. metropolitan areas using Zillow rental data.

The goal is to determine whether rent growth has occurred uniformly
across the country or whether certain regions have experienced
disproportionate increases.

## Load Zillow Rent Dataset

The Zillow Observed Rent Index (ZORI) dataset contains monthly rent
estimates for metropolitan areas across the United States.

For this analysis, we focus on identifying regional trends in rent
growth over time.

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Zillow rent dataset
rent_df = pd.read_csv(
    "Dataset #3 - Metro_zori_uc_sfrcondomfr_sm_month.csv"
)

## Initial Data Inspection

Before performing any analysis, we examine the structure of the
dataset and identify the columns needed for regional analysis.

In [41]:
pd.DataFrame({
    "Dataset": ["Earnings", "Inflation", "Rent"],
    "Rows": [348, 15, 720],
    "Columns": [133, 133, 141]
})

     Dataset  Rows  Columns
0   Earnings   348      133
1  Inflation    15      133
2       Rent   720      141

In [37]:
rent_df[['RegionName','StateName','RegionType']].head(20)

           RegionName StateName RegionType
0       United States       NaN    country
1        New York, NY        NY        msa
2     Los Angeles, CA        CA        msa
3         Chicago, IL        IL        msa
4          Dallas, TX        TX        msa
5         Houston, TX        TX        msa
6      Washington, DC        VA        msa
7    Philadelphia, PA        PA        msa
8           Miami, FL        FL        msa
9         Atlanta, GA        GA        msa
10         Boston, MA        MA        msa
11        Phoenix, AZ        AZ        msa
12  San Francisco, CA        CA        msa
13      Riverside, CA        CA        msa
14        Detroit, MI        MI        msa
15        Seattle, WA        WA        msa
16    Minneapolis, MN        MN        msa
17      San Diego, CA        CA        msa
18          Tampa, FL        FL        msa
19         Denver, CO        CO        msa

## Regional Classification

To compare housing affordability across the United States,
metropolitan areas are grouped into the four Census-style regions:

- Northeast
- Midwest
- South
- West

This classification allows regional rent growth trends to be
compared over time.

In [38]:
rent_df['RegionType'].value_counts()

RegionType
msa        719
country      1
Name: count, dtype: int64

In [43]:
# Check for missing values in key geographic columns
rent_df[['RegionName', 'StateName', 'RegionType']].isnull().sum()

RegionName    0
StateName     1
RegionType    0
dtype: int64

In [44]:
# Number of metropolitan areas represented
rent_df['RegionName'].nunique()

720

In [45]:
rent_df['StateName'].value_counts().head(20)

StateName
TX    48
NC    34
CA    32
PA    30
FL    27
OH    27
NY    25
GA    24
IN    24
TN    23
WI    23
MI    20
WA    19
OR    19
AL    19
MN    18
MO    18
IL    17
OK    17
CO    16
Name: count, dtype: int64

## Filter to Metropolitan Areas

The Zillow dataset contains one national observation ("United States")
and hundreds of metropolitan statistical areas (MSAs).

Because this analysis focuses on regional housing markets,
only metropolitan areas are retained.